/* This class is generated by ObjCTemplar, please do not modify it */

#import "SCExampleDeliveredClass.h"
#import "SCExampleClass.h"

@interface SCExampleDeliveredClass ()

+ (BOOL)_validateID:(NSString *)ID forObject:(SCExampleDeliveredClass *)object error:(NSError **)error;
+ (BOOL)_validateCounter:(int)counter forObject:(SCExampleDeliveredClass *)object error:(NSError **)error;

@end

@implementation SCExampleDeliveredClass

- (instancetype)initWithID:(NSString * _Nonnull)ID error:(NSError **)error  {
    if (![SCExampleDeliveredClass _validateID:ID forObject:nil error:error]) { return nil; }
    
    if (self = [super initWithID:ID er]) {
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}

- (instancetype)initWithExampleClass:(SCExampleDeliveredClass * _Nonnull)exampleClass  {
    NSParameterAssert(exampleClass != nil);

    if (self = [super initWithExampleClass:exampleClass]) { 
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}





- (id)copyWithZone:(NSZone *)zone {
    return self;
}



+ (BOOL)_validateID:(NSString *)ID forObject:(SCExampleDeliveredClass *)object error:(NSError **)error {
    for (id<SCValidator>> *validator in @[ [[SCNonnullValidator alloc] init],  ]) {
        if (![validator validateValue:ID ofProperty:@"ID" forObject:object error:error]) {
            return NO;
        }
    }
    return YES;
}

+ (BOOL)_validateCounter:(int)counter forObject:(SCExampleDeliveredClass *)object error:(NSError **)error {
    for (id<SCValidator>> *validator in @[ [[SCNonnullValidator alloc] init],  ]) {
        if (![validator validateValue:@(counter) ofProperty:@"counter" forObject:object error:error]) {
            return NO;
        }
    }
    return YES;
}



@end



