/* This class is generated by ObjCTemplar, please do not modify it */

#import "SCExampleDeliveredClass.h"
#import "SCValidator.h"
#import "SCPropertyChangesTracker.h"
#import "SCExampleClass.h"

#import "SCNonnullValidator.h"

@interface SCExampleDeliveredClass ()

- (instancetype)initWithBuilder:(SCExampleDeliveredClassBuilder *)builder error:(NSError **)error;
+ (BOOL)_validateID:(NSString *)ID forObject:(SCExampleDeliveredClass *)object error:(NSError **)error;
+ (BOOL)_validateCounter:(int)counter forObject:(SCExampleDeliveredClass *)object error:(NSError **)error;
+ (BOOL)_validateAdditionalValue:(NSValue *)additionalValue forObject:(SCExampleDeliveredClass *)object error:(NSError **)error;

@end

@implementation SCExampleDeliveredClass

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"
- (instancetype)initWithID:(NSString * _Nonnull)ID  {
    NSAssert(NO, @"Forbidden");
    @throw [NSException exceptionWithName:@"Forbidden" reason:@"This object have its own immutable fields" userInfo:nil];
}
#pragma clang diagnostic pop

- (instancetype)initWithID:(NSString * _Nonnull)ID additionalValue:(NSValue * _Nullable)additionalValue error:(NSError **)error  {
    if (![SCExampleDeliveredClass _validateID:ID forObject:nil error:error]) { return nil; }
    if (![SCExampleDeliveredClass _validateAdditionalValue:additionalValue forObject:nil error:error]) { return nil; }
    
    if (self = [super initWithID:ID error:error]) { 
        _additionalValue = additionalValue;
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}

- (instancetype)initWithExampleClass:(SCExampleDeliveredClass * _Nonnull)exampleClass  {
    NSParameterAssert(exampleClass != nil);

    if (self = [super initWithExampleClass:exampleClass]) { 
        _additionalValue = exampleClass->_additionalValue;
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}


- (instancetype)initWithCoder:(NSCoder *)decoder {
    NSError *error = nil;
    
    NSString *ID = [decoder decodeObjectForKey:@"ID"];
    
    NSValue *additionalValue = [decoder decodeObjectForKey:@"additionalValue"];
    
    if (self = [self initWithID:ID additionalValue:additionalValue error:&error]) {
        _description = [decoder decodeObjectForKey:@"description"];
        _components = [decoder decodeObjectForKey:@"components"];
        _counter = [decoder decodeIntForKey:@"counter"];
        
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)encoder {
    [encoder encodeObject:_ID forKey:@"ID"];
    [encoder encodeObject:_description forKey:@"description"];
    [encoder encodeObject:_components forKey:@"components"];
    [encoder encodeInt:_counter forKey:@"counter"];
    [encoder encodeObject:_additionalValue forKey:@"additionalValue"];
    
}



- (instancetype _Nonnull)initWithBuilder:(SCExampleDeliveredClassBuilder * _Nonnull)builder error:(NSError **)error  {
    NSParameterAssert(builder != nil);
    if (![SCExampleDeliveredClass _validateID:builder.ID forObject:nil error:error]) { return nil; }
    if (![SCExampleDeliveredClass _validateAdditionalValue:builder.additionalValue forObject:nil error:error]) { return nil; }
    
    if (self = [self initWithID:builder.ID additionalValue:builder.additionalValue error:error]) { 
        _description = builder.description;
        _components = builder.components;
        _counter = builder.counter;
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}

+ (SCExampleDeliveredClassBuilder * _Nonnull)builder {
    SCExampleDeliveredClassBuilder *builder = [[SCExampleDeliveredClassBuilder alloc] init];

    NSAssert(builder != nil, @"Internal error: builder was not created");
    return builder;
}


- (id)copyWithZone:(NSZone *)zone {
    return self;
}


- (id)mutableCopyWithZone:(NSZone *)zone {
    SCExampleDeliveredClass *exampleClass = self;
    exampleClass = [[SCMutableExampleDeliveredClass allocWithZone:zone] initWithExampleClass:exampleClass];

    NSAssert(exampleClass != nil, @"Internal error: object was not copied");
    return exampleClass;
} 

+ (BOOL)_validateID:(NSString *)ID forObject:(SCExampleDeliveredClass *)object error:(NSError **)error {
    for (NSObject<SCValidator> *validator in @[ [[SCNonnullValidator alloc] init],  ]) {
        if (![validator validateValue:ID ofProperty:@"ID" forObject:object error:error]) {
            return NO;
        }
    }
    return YES;
}

+ (BOOL)_validateCounter:(int)counter forObject:(SCExampleDeliveredClass *)object error:(NSError **)error {
    for (NSObject<SCValidator> *validator in @[ [[SCNonnullValidator alloc] init],  ]) {
        if (![validator validateValue:@(counter) ofProperty:@"counter" forObject:object error:error]) {
            return NO;
        }
    }
    return YES;
}

+ (BOOL)_validateAdditionalValue:(NSValue *)additionalValue forObject:(SCExampleDeliveredClass *)object error:(NSError **)error {
    for (NSObject<SCValidator> *validator in @[ [[SCNonnullValidator alloc] init],  ]) {
        if (![validator validateValue:additionalValue ofProperty:@"additionalValue" forObject:object error:error]) {
            return NO;
        }
    }
    return YES;
}



@dynamic additionalValue;

- (NSValue * _Nullable)additionalValue {
    return _additionalValue;
}

@end


@interface SCMutableExampleDeliveredClass () {
    SCPropertyChangesTracker * _Nonnull _tracker;
}

@end

@implementation SCMutableExampleDeliveredClass

- (instancetype)initWithID:(NSString * _Nonnull)ID additionalValue:(NSValue * _Nullable)additionalValue  error:(NSError **)error  {
    if (self = [super initWithID:ID additionalValue:additionalValue  error:error]) {
        _tracker = [[SCPropertyChangesTracker alloc] init];
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}

- (instancetype)initWithExampleClass:(SCExampleDeliveredClass * _Nonnull)exampleClass  {
    NSParameterAssert(exampleClass != nil);

    if (self = [super initWithExampleClass:exampleClass]) {
        if ([exampleClass isKindOfClass:[SCMutableExampleDeliveredClass class]]) {
            _tracker = [((SCMutableExampleDeliveredClass *)exampleClass)->_tracker copy];
        } else {
            _tracker = [[SCPropertyChangesTracker alloc] init];
        }
    }

    NSAssert(self != nil, @"Internal error: object was not created");
    return self;
}

- (NSArray<NSString *> *)changedKeys {
    return _tracker.changedKeys;
}


- (id)copyWithZone:(NSZone *)zone {
    SCExampleDeliveredClass *exampleClass = self;
    return [[SCExampleDeliveredClass allocWithZone:zone] initWithExampleClass:exampleClass];
}

@dynamic description;

- (void)setDescription:(NSString * _Nullable)description {
    
    if (![_description isEqual:description]) {
        [_tracker beforeValue:_description willBeChangedForKey:@"description"];
        [self willChangeValueForKey:@"description"];
        _description = description;
        [self didChangeValueForKey:@"description"];
        [_tracker newValue:_description wasSetForKey:@"description"];
    }
}

@dynamic components;

- (void)setComponents:(NSArray<NSString *> * _Nonnull)components {
    
    if (![_components isEqual:components]) {
        [_tracker beforeValue:_components willBeChangedForKey:@"components"];
        [self willChangeValueForKey:@"components"];
        _components = components;
        [self didChangeValueForKey:@"components"];
        [_tracker newValue:_components wasSetForKey:@"components"];
    }
}

@dynamic counter;

- (void)setCounter:(int)counter error:(NSError **)error{
    if (![SCExampleDeliveredClass _validateCounter:counter error:error]) { return; }
    
    if (_counter != counter) {
        [_tracker beforeValue:@(_counter) willBeChangedForKey:@"counter"];
        [self willChangeValueForKey:@"counter"];
        _counter = counter;
        [self didChangeValueForKey:@"counter"];
        [_tracker newValue:@(_counter) wasSetForKey:@"counter"];
    }
}

@end



@implementation SCExampleDeliveredClassBuilder

@synthesize additionalValue = _additionalValue;

- (SCExampleDeliveredClass *)buildWithError:(NSError **)error {
    return [[SCExampleDeliveredClass alloc] initWithBuilder:self error:error];
}

@end
