/* This class is generated by ObjCTemplar, please do not modify it */

#import <Foundation/Foundation.h>


@class SCExampleClass;
@class SCExampleDeliveredClass;


@protocol SCExampleSetContainer <NSObject, NSCopying, NSMutableCopying>

@property (nonatomic, strong, retain, readonly) NSSet * _Nullable set;

@end

@interface SCExampleSetContainer : NSObject <SCExampleSetContainer> {
    @protected
    NSSet * _Nullable _set;
 }

- (instancetype _Nullable)init NS_DESIGNATED_INITIALIZER;

- (instancetype _Nonnull)initWithExampleSetContainer:(SCExampleSetContainer * _Nonnull)exampleSetContainer NS_DESIGNATED_INITIALIZER;


@end

@protocol SCMutableExampleSetContainer <SCExampleSetContainer>


- (void)setSet:(NSSet * _Nullable)set error:(NSError * _Nullable __autoreleasing * _Nullable)error;
- (void)addSetObject:(id _Nonnull)setObject error:(NSError * _Nullable __autoreleasing * _Nullable)error;
- (void)removeSetObject:(id _Nonnull)setObject error:(NSError * _Nullable __autoreleasing * _Nullable)error;

@end

@interface SCMutableExampleSetContainer : SCExampleSetContainer <SCMutableExampleSetContainer>

@end

